💬 Add style for pull-quotes
executablebooks/myst-theme pull request #328
Opened 2024-03-11 15:56 UTC by agoose77

I'm not sure if this is best-practice; I'm implying that a pull-quote really is a container-level feature rather than a blockquote-level feature. That follows from how they're implemented in https://github.com/executablebooks/mystmd/pull/961

2024-03-11 18:06 UTC, rowanc1 requested changes
Simple so far! This should be put in the `figures.css` file though I think, as these are additional styles, not overidding tailwind (that is also where other figure css is defined).

2024-03-11 18:12 UTC, rowanc1 commented
We should revert part of this PR to get the kind back on the figure node. maybe prefixing it with `fig-${kind}` or something?

https://github.com/executablebooks/myst-theme/pull/277

And then changing the CSS here:
https://github.com/executablebooks/myst-theme/blob/main/styles/figures.css#L1

Both the `code` and `quote` container kinds are a bit degraded, we can't use the class `table` though, so some sort of prefix would be good.

2024-03-12 12:14 UTC, agoose77 commented
So, I'm guessing that #277 was a deliberate "regression" due to the bare `kind` class being misinterpreted? And, thus, you're suggesting we introduce a custom name like `figure-${kind}` to disambiguate this.

2024-03-12 12:28 UTC, rowanc1 requested changes
A few more things on review!

2024-03-12 12:55 UTC, agoose77 commented on packages/myst-to-react/src/basic.tsx
> +        className={classNames({ subcontainer: node.subcontainer }, { figureName: !!node.kind }, node.class)}
@rowanc1 thanks for the hand-holding on this. I tend to work in a "push first", "check later" style before merging, so you'll probably see a few things like this.

2024-03-12 12:57 UTC, rowanc1 commented on packages/myst-to-react/src/basic.tsx
> +        className={classNames({ subcontainer: node.subcontainer }, { figureName: !!node.kind }, node.class)}
Realize that this was a few minutes after you pushed - I am having coffee, waking up and doing pr reviews on my side... ☕️

2024-03-12 13:17 UTC, rowanc1 approved these changes
Ok - just changesets and this is good from my perspective - can you show a picture of the pullquote and maybe @choldgraf can comment on styles. :)

2024-03-12 13:27 UTC, agoose77 commented
We've added two special kinds of quotes in executablebooks/mystmd#961:

Epigraph:
![image](https://github.com/executablebooks/myst-theme/assets/1248413/be436a9d-0dcb-40a7-aa92-fe6c4e07ff29)

Pull-quote:
![image](https://github.com/executablebooks/myst-theme/assets/1248413/16d9c943-a0dd-4ce1-906e-26cd9200e0c9)

Currently, only pull-quotes are differently styled here, with a larger typeface. We could do more, such as background "quote" characters, but I don't have strong opinions.

2024-03-12 20:18 UTC, choldgraf commented
It's a bit hard to judge design without seeing a live site with pull quotes used in a "real world" scenario, but these seem like a reasonable start. Personally I'd make the pull quote a little bit bigger.

As an example, [here are several examples and inspiration for pull quotes](https://creativepro.com/how-to-attract-attention-pull-quotes/).

Can pull quotes be **placed** a-la columns etc? I often see pull quotes as a sidebar with the text floating around it. For example, here's one from the NYT:

![image](https://github.com/executablebooks/myst-theme/assets/1839645/5a5c0c7a-e95d-4f70-8d7d-99dac4acf657)

I don't think that needs to block this PR but just noting it as a common use-case.

2024-03-12 20:50 UTC, rowanc1 commented on styles/figures.css
> +  font-size: 1.25em;
In addition to being a bit bigger, I think that these should also be in rems!

```suggestion
  font-size: 1.25rem;
```

2024-03-12 20:53 UTC, rowanc1 commented
@choldgraf I have moved this into an issue to track your sources: #329.

Let's increase the size and get it in (after the other PR merges!). We have added the ability to also add classes, which eventually should be able to style these in the near future....!

2024-03-13 15:32 UTC, merged