:bookmark_tabs: Add document outline mobile view
executablebooks/myst-theme pull request #369
Opened 2024-04-23 10:32 UTC by agoose77

Fixes #363 by moving the document outline to the main body of the page.

This PR isn't finished; It moves the outline _above_ the title for books:
![image](https://github.com/executablebooks/myst-theme/assets/1248413/b4ad2935-aaca-4f2c-8745-c0487b302fb8)

To fix this, I need to understand why the `article` theme has its own implementation of `ArticlePage`, instead of re-using that from `@myst-theme/site`. Perhaps @stevejpurves could shed some light? :)

2024-04-24 08:52 UTC, agoose77 commented
@stevejpurves I've replicated the `DocumentOutline` logic for both `article` and `book` themes; now, only the article differs in that it has supporting downloads too.

It feels like `Article` is a fairly high-level component that is theme specific. I wonder if we should just move `Article` from `@myst-theme/site` into the book theme (such that the `article` and `book` themes have their own independent versions). What do you think about that suggestion? Is there something I'm missing?

2024-04-24 09:01 UTC, agoose77 commented
OK, I decided to make that change; I assume that as we built out the themes, it became clear that the article theme needed its own `ArticlePage`, and from there we have been left with the type in `@myst-theme`.

2024-04-24 09:31 UTC, agoose77 commented
I've seen that this is a place where we have project, site, and page frontmatter. I haven't gone through these changes super carefully, so any reviewer would be welcome to cast an eye.

2024-04-24 12:03 UTC, rowanc1 commented
We have 3-4 themes that are dependent on that export from site, anything in book/article cannot be exported.

2024-04-24 12:12 UTC, agoose77 commented
Hmm, OK. @rowanc1 can you nudge on whether the core site export should include this change, or whether I should fork it for the book export?

2024-04-24 14:29 UTC, agoose77 commented
Sure, that's an idea! It might just be that the difference between the two is the addition of downloads.

2024-05-10 15:02 UTC, agoose77 commented
@rowanc1 I'm actually thinking that we shouldn't try and have an `ArticlePage` in the site package. These article pages are built from published components, so users can already re-implement them fairly easily. I think the differences between articles and book pages should better be described by distinct components instead of a "meta" component that encodes the logic for both variants.

Are you OK with that change; dropping the `Article` from `@myst-theme/site`?

2024-05-13 11:05 UTC, stevejpurves commented
@agoose77 I think that suggestion was not to have a single ArticlePage meta component that encoded both sets of changes but indeed to have two distinct page components available in `site` by moving the `article-theme` version up to the package too?

That's leaves us with some naming to sort out but then provides two jumping off points for existing page patterns to be used in downstream themes...?

2024-05-15 04:19 UTC, fwkoch requested changes
Tried this out locally and the mobile view works great, outline appears at the top as expected and the various options seem to be picked up correctly.

Just summarizing from the discussion here, though, I think we need to keep the existing `ArticlePage`, etc, exports from `@myst-theme/site`, so we don't break dependencies from other external themes. @agoose77 - if you think the correct direction is for each theme to define it's own `ArticlePage`, I think it's fine to leave your new `book/.../ArticlePage.tsx` so book theme no longer needs to import it from `@myst-theme/site`. But there isn't any reason to delete the old version from there (can even mark it as `deprecated`?).

This means we won't be breaking dependencies for external themes; we will just be setting an example of how to do things better, and they can upgrade as they see fit.

Other than that and the template option I mentioned in my other comment, all this needs is a changeset, then should be good to go!

2024-05-15 04:19 UTC, fwkoch commented on themes/book/app/types.ts
> +  hide_title_block?: boolean;
Now that these are a nice clear type, it's easy to compare to the `template.yml` - and in doing so, I noticed `hide_title_block` is not declared there as an option. You mind adding that? (I see you already added a couple options to the article `template.yml`, so I assume it's easy.)

2024-05-15 16:34 UTC, agoose77 commented
@fwkoch this is a really helpful review, thank you (and also to @rowanc1).

Could you perhaps help nudge this over the line with the deprecation logic?

2024-05-21 06:22 UTC, fwkoch approved these changes
@agoose77 - thanks for the updates! This is all I was thinking regarding deprecation: https://github.com/executablebooks/myst-theme/blob/agoose77/wip-outline-inline/packages/site/src/pages/Article.tsx#L45

Should all be good to go now, as far as I'm concerned.

2024-05-21 08:35 UTC, agoose77 commented
Are you comfortable merging this? Or would you like a separate review e.g. from @stevejpurves?

2024-05-21 15:41 UTC, merged